// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17dD3iMWaE3DdkBQuRsKBmMpGnFGequ4',
    appId: '1:454919347:web:054b22907383a43aa51cc6',
    messagingSenderId: '454919347',
    projectId: 'moments-mingle-login123',
    authDomain: 'moments-mingle-login123.firebaseapp.com',
    storageBucket: 'moments-mingle-login123.appspot.com',
    measurementId: 'G-M3BWH96KQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByzD5JB6fVzHnOtoKKDvx3YALkc0v2Tzo',
    appId: '1:454919347:android:f0726395088ff12da51cc6',
    messagingSenderId: '454919347',
    projectId: 'moments-mingle-login123',
    storageBucket: 'moments-mingle-login123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhLOowUmlb0B8QGAiOkt-IdbyOXFtUTE',
    appId: '1:454919347:ios:d1ea097b8e9fa28ca51cc6',
    messagingSenderId: '454919347',
    projectId: 'moments-mingle-login123',
    storageBucket: 'moments-mingle-login123.appspot.com',
    iosBundleId: 'com.example.momentsMingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXhLOowUmlb0B8QGAiOkt-IdbyOXFtUTE',
    appId: '1:454919347:ios:cf9b143efdc51f91a51cc6',
    messagingSenderId: '454919347',
    projectId: 'moments-mingle-login123',
    storageBucket: 'moments-mingle-login123.appspot.com',
    iosBundleId: 'com.example.momentsMingle.RunnerTests',
  );
}
